version : "3"

services: 
  newsletter:
    build : .
    command : ["go", "run", ""cmd/newsletter/main.go]
    environment :
      # - OAUTH_CLIENT_ID
      # - OAUTH_CLIENT_SECRET
      # - OPENID_PROVIDER_URL
      # - LOGLEVEL=DEBUG
      # # - PGDATASOURCE=postgres://backend:${POSTGRES_PASSWORD}@postgres/backend?sslmode=disable
      - ADDR=:8080
      - STAGE=local
      - BRANCH=master